name: exciting-turing

version: 0.2.0.0
synopsis: Turing Machine in Haskell, yo...
description: |
  Un *exciting* journey on
  - installing Haskell (with LD errors)
  - using cabal (with weirder cradle errors)
  - using hackage (with even weirder build failures)
  - and more...

author: scarf005 <greenscarf005@gmail.com>
license: MIT
github: 42cursus-youkim/turing
category: Language

ghc-options: >
  -j8 -O0 -Wall -fno-warn-incomplete-uni-patterns -Wno-unused-imports

default-extensions:
  - QuasiQuotes
  - DeriveGeneric
  - BlockArguments
  - LambdaCase
  - InstanceSigs
  - MultiWayIf
  - DeriveGeneric
  - DeriveAnyClass

dependencies:
  - base >= 4.14 && < 5
  - text
  - containers
  - bytestring
  - PyF >= 0.11.0
  - terminal-size
  - pretty-terminal
  - optparse-applicative
  - aeson >= 2.1.0

executable:
  main: Main.hs
  source-dirs: src

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - QuickCheck
      - hspec == 2.*
      - HUnit >= 1.6.0.0
